### ISSUE TITLE
MongoError: unauthorized

### ISSUE THREAD

**Issue by cyllu2** [arunoda/meteor-up#445]
Trying to deploy to Digital Ocean with Mongo database hosted at Compose.

Logs: 
> /opt/cardmaker/app/programs/server/node_modules/fibers/future.js:278
>                                                throw(ex);
>                                                     ^
> MongoError: unauthorized
>    at Object.Future.wait (/opt/cardmaker/app/programs/server/node_modules/fibers/future.js:398:15)
>   at [object Object]._.extend.count (packages/mongo/mongo_driver.js:1002:1)
>    at [object Object].Cursor.(anonymous function) [as count] (packages/mongo/mongo_driver.js:812:1)
>    at app/server/seeds.js:3:22
>    at /opt/cardmaker/app/programs/server/boot.js:229:5

Noteworthy is that I **can** connect to my Mongo database using wait-for-mongo

What could be wrong?

**Comment by cyllu2** [comment]
The only thing I can think of was wrong was that I used a sandbox database for testing purposes. It worked when I used the real deal.
