### ISSUE TITLE
Timing out on uploading bundle

### ISSUE THREAD

**Issue by cyllu2** [arunoda/meteor-up#469]
I'm using DigitalOcean without ssh keys to deploy, and it worked a couple of weeks ago. I made a few unimportant changes and tried to deploy again, but this time it times out.

> events.js:72
>       throw er; // Unhandled 'error' event
>              ^
>Error: Timed out while waiting for handshake
>    at null._onTimeout (/home/ubuntu/.nvm/v0.10.35/lib/node_modules/mup/node_modules/nodemiral/node_modules/ssh2/lib/client.js:138:17)
>    at Timer.listOnTimeout [as ontimeout] (timers.js:112:15)

What could be the problem? Haven't made any changes in my settings so something must have changed on this end.

**Comment by cyllu2** [comment]
This seems to be an issue with my work environment, since it worked perfectly from another workstation. Still would appreciate some pointers on what could have gone wrong...
